name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar que el token esté presente (debug temporal)
      run: |
        if [ -z "$DISCORD_TOKEN_ARELITTA" ]; then echo "Token no presente"; exit 1; else echo "Token presente"; fi
      env:
        DISCORD_TOKEN_ARELITTA: ${{ secrets.DISCORD_TOKEN_ARELITTA}}

    - name: Run bot
      env:
        DISCORD_TOKEN_ARELITTA: ${{ secrets.DISCORD_TOKEN_ARELITTA}}
      run: |
        python bot.py
