name: Deploy Bot

on:
  push:
    branches:
      - main  # o la rama que usas para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_ARELITTA }}
      run: |
        python bot.py
